// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class InventoryLog
{
    public int LogId { get; set; }

    public int ProductId { get; set; }

    public int QuantityChange { get; set; }

    public string MovementType { get; set; }

    public int? ReferenceId { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedDate { get; set; }

    public int UserId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}