// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class Modifier
{
    public int ModifierId { get; set; }

    public int GroupId { get; set; }

    public string Name { get; set; }

    public decimal AdditionalPrice { get; set; }

    public bool IsActive { get; set; }

    public virtual ModifierGroup Group { get; set; }

    public virtual ICollection<OrderItemModifier> OrderItemModifiers { get; set; } = new List<OrderItemModifier>();
}