// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class ModifierGroup
{
    public int GroupId { get; set; }

    public string Name { get; set; }

    public int MinSelections { get; set; }

    public int MaxSelections { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Modifier> Modifiers { get; set; } = new List<Modifier>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}