// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class OrderItemModifier
{
    public int OrderItemModifierId { get; set; }

    public int OrderItemId { get; set; }

    public int ModifierId { get; set; }

    public string ModifierName { get; set; }

    public decimal AdditionalPrice { get; set; }

    public virtual Modifier Modifier { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}