// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class Outlet
{
    public int OutletId { get; set; }

    public int BranchId { get; set; }

    public string Name { get; set; }

    public string DeviceIdentifier { get; set; }

    public bool IsActive { get; set; }

    public string Ptunumber { get; set; }

    public string Minnumber { get; set; }

    public string SerialNumber { get; set; }

    public virtual Branch Branch { get; set; }
}