// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public decimal? UnitValue { get; set; }

    public string UnitOfMeasure { get; set; }

    public string Barcode { get; set; }

    public decimal Price { get; set; }

    public decimal? CostPrice { get; set; }

    public int StockQuantity { get; set; }

    public string Sku { get; set; }

    public int? TaxId { get; set; }

    public int ReorderLevel { get; set; }

    public bool IsActive { get; set; }

    public string ImageUrl { get; set; }

    public string ProductType { get; set; }

    public bool IsKitchenItem { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<InventoryLog> InventoryLogs { get; set; } = new List<InventoryLog>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Taxis Tax { get; set; }

    public virtual ICollection<ModifierGroup> Groups { get; set; } = new List<ModifierGroup>();
}