// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS.Api.Models;

public partial class UnitOfMeasure
{
    public int UomId { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }
}